### ISSUE TITLE
If Wifi Enabled, you can't see Ethernet stats in status bar

### ISSUE THREAD

**Issue by Midnex** [noroadsleft000/gnome-network-stats#10]
Using PopOS! 21.04
Kernel 5.13.0-7614

When wifi is enabled, the status bar defaults to WiFi, can can not be changed to Ethernet, even if wifi is not being used.

I generally have my work laptop on wifi, but when I am in the office it connects to a docking station, wifi stays on, but ethernet is used, and gnome-network-stats detects it, but will not change the status bar, and I can not find a way without disabling wifi.

**Comment by noroadsleft000** [comment]
@Midnex Thanks for reporting.
I understand that is a lack of functionality. I will add to TODO list.

**Comment by Midnex** [comment]
Thanks!

**Comment by Midnex** [comment]
Sorry for the late reply, seems to be working great. Thanks for the quick fix, and again sorry for the slow response.
