### ISSUE TITLE
TypeError: resetTimeWidget.add is not a function

### ISSUE THREAD

**Issue by timur-tabi** [noroadsleft000/gnome-network-stats#18]
When trying to open the settings for this extension, I get this error:

```
TypeError: resetTimeWidget.add is not a function

Stack trace:
  PrefsApp@/home/ttabi/.local/share/gnome-shell/extensions/network-stats@gnome.noroadsleft.xyz/prefs.js:110:25
  buildPrefsWidget@/home/ttabi/.local/share/gnome-shell/extensions/network-stats@gnome.noroadsleft.xyz/prefs.js:206:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

```

**Comment by noroadsleft000** [comment]
@timur-tabi  Thanks for filling the bug.
Can you give us some more details  ? like.
```
- OS version.
- Shell version.
- Extension version.
- and frequency of this issue.
```

**Comment by noroadsleft000** [comment]
@timur-tabi

Ubuntu 21.10 comes with GNOME 40 default shell version.
There are some breaking changes at API level. Would need some time to fix this for 21.10.

**Comment by noroadsleft000** [comment]
@timur-tabi  If you are a developer, can you try out latest version from main ?

**Comment by timur-tabi** [comment]
I'm not a *Gnome* developer, but I'll try.

**Comment by timur-tabi** [comment]
I rebooted and somehow the addon is now installed.  I can open the settings now without error.

On a side note, I don't actually use this add-on any more because it doesn't give me separate displays of download and upload speeds.  It's either one or the other, or a combined speed which I think is useless.

**Comment by noroadsleft000** [comment]
@timur-tabi 
Thanks for trying out.
We have an outstanding request for showing both speeds side by side.
I hope you would like to give it a try in future. closing this bug now.
