### ISSUE TITLE
wrong speed show

### ISSUE THREAD

**Issue by hhurma** [noroadsleft000/gnome-network-stats#3]
hi, the download / upload speed is showing wrong. I'm downloading with 5 megabyte / s, it shows kb / s.

**Comment by noroadsleft000** [comment]
Thanks for reporting the bug. It was broken due to some intermediate changes.

Fixed with this.
https://github.com/noroadsleft000/gnome-network-stats/commit/f49e3d02f074e83de235e53e0dc33f923806db7b

Please try out latest version 6.
