### ISSUE TITLE
Compatibility with Gnome 41

### ISSUE THREAD

**Issue by lp35** [noroadsleft000/gnome-network-stats#31]
Hello,

Is it possible to make this extension compatible with Gnome 41? Thanks!

**Comment by noroadsleft000** [comment]
@lp35  Yes,
 there are no any major changes in API's from gnome 40 to 41. I don't have a machine for testing on gnome 41.
Will release it after testing on gnome 41.

Meanwhile can you try out this build
[network-stats@gnome.noroadsleft.xyz.shell-extension.zip](https://github.com/noroadsleft000/gnome-network-stats/files/7824057/network-stats%40gnome.noroadsleft.xyz.shell-extension.zip)
```
gnome-extensions install network-stats%40gnome.noroadsleft.xyz.shell-extension.zip
```
Then restart the gnome shell, steps [here](https://github.com/noroadsleft000/gnome-network-stats#known-issues)

**Comment by noroadsleft000** [comment]
Support added in extension version 12.
