### ISSUE TITLE
reset data each reboot

### ISSUE THREAD

**Issue by pommedefrance** [noroadsleft000/gnome-network-stats#42]
Hi
this a very nice extension, nevertheless each time i reboot my linux, the counter starts again to 0 (amount of data used)
even if i choose "never"..and same for the other..
do you know why ?
thks !

**Comment by noroadsleft000** [comment]
Fixed in version > 15.

**Comment by pommedefrance** [comment]
it seems working :-) (at least for keeping the data, we'll see reset for a month)
thks a lot !
