### ISSUE TITLE
Extension incompatible with GNOME 44.0

### ISSUE THREAD

**Issue by Flimm** [noroadsleft000/gnome-network-stats#51]
I've upgraded to Ubuntu 23.04, which uses GNOME 44.0 . This extension is no longer enabled, because it is marked as incompatible with this version of GNOME.

**Comment by rtgiskard** [comment]
a temporary solution: edit metadata.json, append 44 to `shell-version`

**Comment by noroadsleft000** [comment]
version 20
Added support for gnome version 44.

**Comment by Flimm** [comment]
Thank you so much!
