### ISSUE TITLE
Extension incompatible with GNOME 45

### ISSUE THREAD

**Issue by Flimm** [noroadsleft000/gnome-network-stats#55]
I've installed the latest version of Ubuntu, which is 23.10, and it comes with GNOME 45. This extension doesn't currently support GNOME 45. I've heard that GNOME 45 introduces some changes to extension compatibility, so it may take a bit more work than usual to upgrade this extension.

**Comment by Pommede** [comment]
same issue :-(
i'm sad because this extension is irreplaceable !

**Comment by noroadsleft000** [comment]
Extension is easy to install from source code. you can bump up the gnome in [manifest.json](https://github.com/noroadsleft000/gnome-network-stats/blob/main/metadata.json) and then run
`make install`
Check [README.md](https://github.com/noroadsleft000/gnome-network-stats/blob/main/README.md) for installation details.

**Comment by noroadsleft000** [comment]
version 21 available in extension store.

**Comment by Pommede** [comment]
where version 21 ?? 
thks !
