### ISSUE TITLE
Extension incompatible with GNOME 46

### ISSUE THREAD

**Issue by Shished** [noroadsleft000/gnome-network-stats#59]
Gnome 46 is available in Arch for some weeks and this extension doesn't currently support GNOME 46. I've heard that GNOME 46 introduces some changes to extension compatibility, so it may take a bit more work than usual to upgrade this extension.

**Comment by noroadsleft000** [comment]
waiting for the official release. meanwhile you can try it out by increasing version in metadata.json

**Comment by noroadsleft000** [comment]
branch: feature/gnome-45
Already submitted to gnome store for review. Hopefuly it will be avaialble in couple of day.

**Comment by noroadsleft000** [comment]
New version available in extension store.
